language:
  python

python:
  - '3.6.1'

install:
  - pip install -r requirements.txt

script:
  # - coverage run gateway/manage.py test
  # - coverage report -m
  - python gateway/manage.py test

  # - coverage run user/manage.py test
  # - coverage report -m
  - python user/manage.py test

  # - coverage run article/manage.py test
  # - coverage report -m
  - python article/manage.py test

  # - coverage run journal/manage.py test
  # - coverage report -m
  - python journal/manage.py test

  # - coverage run publisher/manage.py test
  # - coverage report -m
  - python publisher/manage.py test