language:
  python

python:
  - '3.6.1'

install:
  - pip install -r requirements.txt

script:
  - cd user
  - coverage run manage.py test
  #- coverage report -m

  - cd ../article
  - coverage run manage.py test
  #- coverage report -m

  - cd ../journal
  - coverage run manage.py test
  #- coverage report -m

  - cd ../publisher
  - coverage run manage.py test
  #- coverage report -m

  - cd ../gateway/backend
  - coverage run manage.py test
  #- coverage report -m