# Generated by Django 2.2.5 on 2019-10-18 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uuid', models.UUIDField(unique=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('author_uuid',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('published', models.DateField()),
                ('journal', models.UUIDField()),
                ('authors', models.ManyToManyField(to='api.Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('title', 'added'),
            },
        ),
    ]
